# Generated by Django 4.2.1 on 2023-05-24 05:22

from django.db import migrations


def create_tags_and_categories(apps, schema_editor):
    Tag = apps.get_model('posts', 'Tag')
    Category = apps.get_model('posts', 'Category')

    # Create tags
    tags = [
        'Technology',
        'Science',
        'Health',
        'Travel',
        'Food',
        'Fashion',
        'Sports',
        'Music',
        'Movies',
        'Books',
        'Art',
        'Photography',
        'Nature',
        'Business',
        'Lifestyle',
    ]
    for tag in tags:
        Tag.objects.create(name=tag)

    # Create categories
    categories = [
        'News',
        'Tutorials',
        'Reviews',
        'How-to Guides',
        'Personal Stories',
        'Opinion',
        'Inspirational',
        'Educational',
        'Entertainment',
        'Tips and Tricks',
        'Events',
        'Interviews',
        'Product Updates',
        'Case Studies',
        'Featured Stories',
    ]
    for category in categories:
        Category.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_tags_and_categories),
    ]
